### ISSUE TITLE
Mi cloud message sync Mi9 SE

### ISSUE THREAD

**Issue by gatarba** [ashtefan/Romanian_MIUI_11#12]
Since updated to Android 10, the messages cannot be synced with mi cloud.

**Comment by ygorigor** [comment]
@gatarba în English language is working?

**Comment by ashtefan** [comment]
I don't sync messages or call history in Xiaomi Cloud so I cannot confirm.

**Comment by gatarba** [comment]
> @gatarba în English language is working?

No, I guess it's a general bug
