### ISSUE TITLE
Traducere gresita

### ISSUE THREAD

**Issue by Salieri99** [ashtefan/Romanian_MIUI_11#14]
In sunet și vibrare, setați adiționale este optiunea "Sunet acumulator încărcat complet". Credeam că mă va anunța când se incarca complet telefonul. Dar este doar optiunea privind sunetele cand punem sau scoatem telefonul de la încărcat.

Sunt pe xiaomi.eu stable 11.3.3

**Comment by ashtefan** [comment]
Va fi disponibila modificarea in urmatoarea versiune xiaomi.eu
